server:
  port: 8080

spring:
  application:
    name: CrmApplication

  data:
    mongodb:
      uri: mongodb+srv://kuldeep_ydv32:Demo123@demo.fwkrxhd.mongodb.net/Demo?retryWrites=true&w=majority&appName=Demo
      database: Demo
